"""Initial migration

Revision ID: be4b8be10f65
Revises: 
Create Date: 2025-08-05 10:19:41.846897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be4b8be10f65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create auth schema first
    op.execute('CREATE SCHEMA IF NOT EXISTS auth')
    
    # Create tables without foreign keys first to resolve circular dependencies
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=48), nullable=False),
    sa.Column('last_name', sa.String(length=48), nullable=False),
    sa.Column('username', sa.String(length=48), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False, comment='Password hash (bcrypt/argon2)'),
    sa.Column('role', postgresql.ENUM('ADMIN', 'WAREHOUSE', 'ANALYTIC', 'CONTENT', 'GUEST', name='user_roles', schema='auth'), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True, comment='Ссылка на Компанию'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Время создания записи'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Время последнего обновления'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_table('workspace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='Владелец аккаунта'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Время создания записи'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Время последнего обновления'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='auth'
    )
    
    # Add foreign key constraints after tables are created
    op.create_foreign_key('fk_user_workspace_id', 'user', 'workspace', ['workspace_id'], ['id'], source_schema='auth', referent_schema='auth', ondelete='CASCADE')
    op.create_foreign_key('fk_workspace_owner_id', 'workspace', 'user', ['owner_id'], ['id'], source_schema='auth', referent_schema='auth', ondelete='SET NULL')
    op.create_table('workspace_user',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Время создания записи'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Время последнего обновления'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['auth.workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id'),
    schema='auth'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_user', schema='auth')
    op.drop_table('workspace', schema='auth')
    op.drop_table('user', schema='auth')
    # Drop the auth schema
    op.execute('DROP SCHEMA IF EXISTS auth CASCADE')
    # ### end Alembic commands ###
